refactored intersections.metta  func
iCog-Labs-Dev/metta-moses-reduction pull request #107
Opened 2024-09-23 14:53 UTC by Nardos-serkalem

2024-09-24 07:38 UTC, Yagth requested changes
I found the issue. You didn't remove the previous `intersections` function after you implemented the new one. Make sure to do that, add your test cases in the appropriate file I told you and  then test it locally. If everything is well, update your PR :)

2024-09-24 07:38 UTC, Yagth commented on utilities/tree-helpers.metta
> +;; testcase
Remove this test cases from this file. Intersections' test file is found in the `enf-reducer/tests/helper-functions` add the following test cases and also some more if you can.
```scheme
(intersections Nil) 
(intersections (Cons (TreeNode (Value Nil False AND) (Cons (TreeNode (Value A True LITERAL) Nil Nil) Nil) Nil) (Cons (TreeNode (Value Nil False AND) (Cons (TreeNode (Value A True LITERAL) Nil Nil) Nil) Nil) Nil)))
```

Writing test cases like the one above isn't the only thing you need to do. Take a look in the file and make sure you use `assertEqual` to write your test cases.

2024-10-02 08:17 UTC, Yagth requested changes

2024-10-02 08:17 UTC, Yagth commented on utilities/tree-helpers.metta
> +
Remove Unnecessary spaces between a function definition to be consistent with our code base.

2024-10-02 08:17 UTC, Yagth commented on utilities/tree-helpers.metta
> +
Remove this line too

2024-10-02 08:17 UTC, Yagth commented on utilities/tree-helpers.metta
> +
Same here

2024-10-02 08:17 UTC, Yagth commented on utilities/tests/tree-helpers-test.metta
> +!(assertEqual(intersections Nil) Nil )
Add a space between `assertEqual` and `(intersections ... )`

2024-10-02 08:17 UTC, Yagth commented on utilities/tree-helpers.metta
> +
Same here. Remove this line

2024-10-02 08:17 UTC, Yagth commented on utilities/tree-helpers.metta
> +
Remove this line

2024-10-02 08:57 UTC, Nardos-serkalem reviewed
I have  implemented the requested changes and updated the code accordingly.

2024-10-02 09:14 UTC, Yagth approved these changes

2024-10-02 11:26 UTC, merged