Implementation for commandSetIterator function.
iCog-Labs-Dev/metta-moses-reduction pull request #59
Opened 2024-08-07 14:00 UTC by samwondim

2024-08-12 14:01 UTC, Yagth requested changes

2024-08-12 15:01 UTC, samwondim commented
@Yagth  The issues are fixed.

2024-08-12 15:09 UTC, Yagth commented on enf-reducer/RTEHelpers.metta
> +(= (commandSetIterator $children $localCommandSet)(
Better but this still can be better. You can also define the function with different cases with out using the `case` key word. like so
```
(= (commandSetIterator Nil $localCommandSet) $localCommandSet)
(= (commandSetIterator (Cons $x $xs) $localCommandSet 
    (...)
)
```

2024-08-12 15:10 UTC, Yagth reviewed
You can still make the `commandSetIterator` function better without even using case.

2024-08-12 15:11 UTC, Yagth commented on enf-reducer/RTEHelpers.metta
> +          setUnion (getGuardSet (head $children)) (commandSetIterator (tail $children) $localCommandSet)
Isn't the `setUnion` function expecting a `treeIsMember` function here?

2024-08-13 07:58 UTC, Yagth approved these changes

2024-08-13 07:59 UTC, merged