Added the function orSubTreeIterator
iCog-Labs-Dev/metta-moses-reduction pull request #63
Opened 2024-08-09 08:55 UTC by Liya-F

- Added the function orSubTreeIterator inside the RTEHelpers file
- It is the reimplementation of the same function found in the python file

2024-08-10 10:50 UTC, EyobAshenaki requested changes
**Issues**:
There are multiple undefined functions in this PR, namely `commandSetIterator`, `orSubTreeElegance`, `orSubTreeIterator`, `andSubTreeElegance` and `andSubTreeIterator`. 

**Requested Changes**:
- Implement the above missing functions 
- Include at least 2 test cases for all implemented functions

2024-08-10 12:16 UTC, Yagth commented
@EyobAshenaki Those functions are being implemented by other people, we can test them until they are done. What do you think is better? Should we merge the codes and test them later or should we wait until all of them are done and do the test then merge them?

2024-08-10 12:28 UTC, EyobAshenaki commented
The latter case seems like the best choice. It would save us from a headache later on.

2024-08-10 12:32 UTC, Yagth commented
But we would still face so e interdependence between the functions. For instance, the `orSubTreeElegance` needs to call the `reduceToElegance` algorithm which can't be complete without the `orSubTreeElegance` itself. What if we could replace the function calls with the appropriate return type of the function stored on a variable, instead of calling the functions we put a mock data on a variable and test whether the function works or not?

2024-08-10 15:57 UTC, EyobAshenaki commented
I think that's an acceptable compromise time wise.

2024-08-10 16:01 UTC, Yagth commented
> @EyobAshenaki But we would still face the same problem letter on because of the interdependence between the functions. For instance, the `orSubTreeElegance` needs to call the `reduceToElegance` algorithm which can't be complete without the `orSubTreeElegance` itself. What if we could replace the function calls with the appropriate return type of the function stored on a variable, instead of calling the functions we put a mock data on a variable and test whether the function works or not?

@Liya-F can you make sure to use a mock data instead of calling the functions that aren't implemented yet? Refactor the code this way, test it out using one or two test cases and update your PR.

2024-08-12 08:50 UTC, Liya-F commented
- I have replaced the unimplemented functions with mock data. Specifically, I have assigned $action with ADVANCE, which will be the value returned by the functions once they are implemented.
- I have commented out the code that calls these functions for future use.
- I have also added test cases for both

2024-08-14 09:17 UTC, EyobAshenaki commented on enf-reducer/RTEHelpers.metta
> +(: orSubTreeIterator(-> Tree (List Tree) Tree (List Tree) (List Tree) Signal))
the type definition should return a tuple containing Signal and Tree

2024-08-14 09:18 UTC, EyobAshenaki commented on enf-reducer/RTEHelpers.metta
> +(: andSubTreeIterator(-> (List Tree) Tree (List Tree) (List Tree) (-> (List Tree) Tree (List Tree) (List Tree) Number Signal)))
the type definition should return a tuple containing Signal and Tree

2024-08-14 09:18 UTC, EyobAshenaki commented on enf-reducer/RTEHelpers.metta
> +(: andSubTreeIterator(-> (List Tree) Tree (List Tree) (List Tree) Number Signal))
the type definition should return a tuple containing Signal and Tree

2024-08-14 09:20 UTC, EyobAshenaki requested changes
fix the type definition for the implemented functions

2024-08-14 12:05 UTC, Liya-F commented
> fix the type definition for the implemented functions

I have fixed the type definition for both functions.

2024-08-14 13:39 UTC, EyobAshenaki approved these changes

2024-08-14 13:41 UTC, merged